item/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

app_name = 'item'

urlpatterns = [
    url(r'^doget/(?P<param1>.*)$', views.doget_execute, name='item_doget'),
    url(r'^red/$', views.showredirect),
    url(r'^red2/$', views.showredirect2),
    url(r'^red3/$', views.showredirect3),
    url(r'^dg/(?P<param1>.*)/$', views.doget_execute, name='doget'),
    url(r'^child/$', views.showchild),
    url(r'^post_e/$', views.dopost_execute, name='post_e'),
    url(r'^input/$', views.show_input),
    url(r'^input_e/$', views.show_inputerr),
    url(r'^$', views.SampleTemplateView.as_view()),
    url(r'^index/$', TemplateView.as_view(template_name='html/index.html')),
    url(r'^list1/$', views.ItemModelListView.as_view()),
    url(r'^list2/$', views.ItemQueryListView.as_view()),
    url(r'^name/([\w-]+)/$', views.ItemNameListView.as_view()),
    url(r'^list/(?P<pk>[\d]+)/$', views.ItemDetailView.as_view()),
    url(r'^form/$', views.dopost_view),
    url(r'^conf/$', views.confirm),
    url(r'^thanks/$', TemplateView.as_view(template_name='html/thanks.html'), name='thanks'),
    url(r'^f_view/$', views.InputFormView.as_view()),
    url(r'^item_f/$', views.ItemFormView.as_view()),
]

pj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from item import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # ex: http://127.0.0.1:8000/wel
    url(r'^wel$', views.welcome, name='welcome'),
    # ex: http://127.0.0.1:8000/doget/12345
    url(r'^doget/(.*)$', views.doget_execute, name='doget_e'),
#     url(r'^doget/(?P<param1>.*)$', views.doget_execute, name='doget_p'),
    url(r'^item/', include('item.urls')),
    # ex: http://127.0.0.1:8000/showtemp1/
    url(r'^showtemp1/$', views.showtemp1),
    # ex: http://127.0.0.1:8000/showtemp1sc/
    url(r'^showtemp1sc/$', views.showtemp1sc),
    url(r'show/$', views.welcome, name='wel'),

]

item/models/model_file.py
from django.db import models
from django.db.models import ForeignKey, ManyToManyField, OneToOneField

class Item(models.Model):
    name = models.CharField(max_length=256)
    price = models.IntegerField()

    def __str__(self):
        return 'name[{0}] price[{1}]'.format(self.name, self.price)

class Category(models.Model):
    name = models.CharField(max_length=256)

class Product(models.Model):
    name = models.CharField(max_length=256)
    category = ForeignKey(Category, on_delete=models.CASCADE, related_name='products')

class Authority(models.Model):
    name = models.CharField(max_length=256)

class Emp(models.Model):
    name = models.CharField(max_length=256)
    authoritys = ManyToManyField(Authority, related_name='emps')

class Password(models.Model):
    value = models.CharField(max_length=16)

class Account(models.Model):
    name = models.CharField(max_length=50)
    password = OneToOneField(Password)

item/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import models
from item.models import Item

class InputForm(forms.Form):
    param1 = forms.CharField()

class SampleForm(forms.Form):
    p1 = forms.CharField()
    p2 = forms.CharField(widget=forms.Textarea)
    p3 = forms.MultipleChoiceField(choices=(('1', '赤'), ('2', '黄色'),('3', '青')),
                                   widget=forms.CheckboxSelectMultiple)
    p4 = forms.ChoiceField(choices=(('1', '赤'), ('2', '黄色'),('3', '青')),
                           widget=forms.RadioSelect)
    p5 = forms.ChoiceField(choices=(('1', '赤'), ('2', '黄色'),('3', '青')),
                           widget=forms.Select)
    p6 = forms.FileField()

class InputForm2(forms.Form):
    param1 = forms.IntegerField()

    def clean_param1(self):
        param1 = self.cleaned_data['param1']
        if not (0 < param1 < 10):
            raise ValidationError('範囲エラー')
        return param1

class InputForm3(forms.Form):
    param1 = forms.IntegerField(
            max_value=10,
            error_messages={
                    'required': '必須入力です',
                    'max_value': '最大値を超えています'})

class InputFormValid(forms.Form):
    param1 = forms.IntegerField(max_value=10)
    param2 = forms.CharField(required=False)
    
class ItemForm(models.ModelForm):
    name = forms.CharField(label='名前')
    price = forms.IntegerField(label='価格')
    class Meta:
        model = Item
        fields = ('name', 'price')

item/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.http.response import HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView, ListView, DetailView, FormView
from item.models import Item
from item.forms import SampleForm, InputForm, InputForm2, InputForm3, ItemForm

def welcome(request):
    return HttpResponse('welcome')

def doget_execute(request, param1):
    return HttpResponse(param1)

def showtemp1(request):
    c = {
         'key1' : 'hello everyone',
    }
    return render(request, 'template1.html', c)

def showtemp1sc(request):
    return render(request, 'template1.html', {'key1': 'hello everyone'})

def showredirect(request):
    return redirect('/show')

def showredirect2(request):
    return redirect('wel')

def showredirect3(request):
    return render(request, 'templateform.html')

def showchild(request):
    return render(request, 'child.html')

@csrf_protect
def dopost_execute(request):
    param = request.POST['message']
    return render(request, 'result.html', {'message': param})

def show_input(request):
    return render(request, 'input.html')

def show_inputerr(request):
    return render(request, 'input_tokenerror.html')

def csrf_failure(request, reason=''):
    c = {'message': 'トークンエラー'}
    return render(request, '403_csrf.html', c)

# TemplateView
class SampleTemplateView(TemplateView):
    template_name = 'html/index.html'

# ListView_1
class ItemModelListView(ListView):
    template_name = 'item_list.html'
    model = Item
    context_object_name = 'items'

# ListView_2
class ItemQueryListView(ListView):
    template_name = 'item_list.html'
    queryset = Item.objects.all().order_by('id')
    context_object_name = 'items'

class ItemNameListView(ListView):
    template_name = 'item_list.html'
    context_object_name = 'items'

    def get_queryset(self):
        return get_list_or_404(Item, name=self.args[0])

# DetailView
class ItemDetailView(DetailView):
    template_name = 'item_detail.html'
    model = Item
    context_object_name = 'item'

def dopost_view(request):
    form = SampleForm()
    return render(request, 'template.html', {'form': form})

def confirm(request):
#     form = InputForm(request.POST)
#     form = InputForm2(request.POST)
    form = InputForm3(request.POST)
#     form = InputFormValid(request.POST)
    if not form.is_valid():
        return render(request, 'form_param.html', {'form': form})
    msg = form.cleaned_data['param1']
    return render(request, 'form_param.html', {'form': form, 'message': msg})

class InputFormView(FormView):
    form_class = InputForm
    template_name = 'input_form_v.html'
    success_url = '/item/thanks'

class ItemFormView(FormView):
    form_class = ItemForm
    template_name = 'item_form.html'

    def form_valid(self, form):
        form.save()
        return redirect('item:thanks')

item/templates/403_csrf.html
<html>
<head></head>
<body>
<h2>トークンエラーが発生しました</h2>
{{ message }}
</body>
</html>

item/templates/child.html
{% extends "parents.html" %}
{% block title %}
子供服
{% endblock %}
{% block content %}
<table border="1">
  <tr>
    <td>1</td>
    <td>靴</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Tシャツ</td>
  </tr>
</table>
{% endblock %}

item/templates/form_param.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>InputForm</title>
</head>
<body>
  <h4>入力</h4>
  <form action="" method="post">
    {% csrf_token %}
    {% for error in form.param1.errors %}
    <div style="color:red">  {{ error }} </div>
    {% endfor %}
    <table>
    {{ form.param1.label }}{{ form.param1 }}
    </table>
    <br>
    <input type="submit" /><br>
  </form>
  {{ message }}
</body>
</html>

item/templates/html/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>スタートページ</title>
</head>
<body>
<h1>Hello World!</h1>
<div>これからDjangoを使用したWebアプリケーション作成をはじめます。</div>
</body>
</html>

item/templates/html/thanks.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Thanks!</title>
</head>
<body>
<h4>処理が完了しました！</h4>
</body>
</html>

item/templates/input.html
<html>
<head></head>
<body>
<form action="{% url 'item:post_e' %}" method="post">
  {% csrf_token %}
  <input name="message" />
  <input type="submit" />
</form>
</body>
</html>

item/templates/input_form_v.html
<html>
<head></head>
<body>
  <h4>入力</h4>
  <form method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" />
  </form>
</body>
</html>

item/templates/input_tokenerror.html
<html>
<head></head>
<body>
<form action="{% url 'item:post_e' %}" method="post">
  <input name="message" />
  <input type="submit" />
</form>
</body>
</html>

item/templates/item_detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>DetailView</title>
</head>
<body>
<table border="1">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>price</th>
  </tr>
  <tr>
      <td>{{ item.id }}</td>
      <td>{{ item.name }}</td>
      <td>{{ item.price }}</td>
  </tr>
</table>
</body>
</html>

item/templates/item_form.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<form method="post">
{% csrf_token %}
<table>
  {{ form }}
</table>
<input type="submit" />
</form>
</body>
</html>

item/templates/parents.html
<html>
<head><title>parents.html</title></head>
<body>
<h2>
  {% block title %}
     タイトル
  {% endblock %}
</h2>
<div>
  {% block content %}
     内容
  {% endblock %}
</div>
</body>
</html>

item/templates/result.html
<html>
<head></head>
<body>
入力した値：{{ message }}
</body>
</html>

item/templates/template.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Sample Form</title>
</head>
<body>
<h4>入力</h4>
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" />
</form>
</body>
</html>

item/templates/templatefor.html
<html>
<head></head>
<body>
{% for e in key1 %}
  {{ e  }}<br>
{% endfor %}
</body>
</html>

item/templates/templateform.html
<html>
<head></head>
<body>
 <a href="{% url 'wel' %}">Welcome</a><br>
 <form action="{% url 'item:doget' 'hogehoge' %}" method="get">
 <input type="submit">
 </form>
</body>
</html>

item/templates/templateif.html
<html>
<head></head>
<body>
{% if key1 == 'goodmorning everyone' %}
  おはようございます
{% else %}
  こんにちは
{% endif %}
</body>
</html>